language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

script:
   - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace